module.exports = {
  NULL_VALUE: "필요한 값이 없습니다.",
  OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",

  /* 회원가입 */
  SIGN_UP_SUCCESS: "회원 가입 성공.",
  SIGN_UP_FAIL: "회원 가입 실패.",
  SIGN_IN_SUCCESS: "로그인 성공.",
  SIGN_IN_FAIL: "로그인 실패.",
  USER_LOGOUT: "사용자 로그아웃",
  ALREADY_ID: "존재하는 ID 입니다.",
  CHECK_ID_SUCCESS: "ID 중복검사 성공",
  CHECK_ID_FAIL: "ID 중복검사 실패",
  ALREADY_PHONE: "존재하는 핸드폰 번호 입니다.",
  NO_USER: "존재하지않는 유저 id 입니다.",
  ALREADY_EMAIL: "이미 존재하는 이메일 입니다.",
  CHECK_EMAIL_SUCCESS: "Email 중복검사 성공",
  CHECK_EMAIL_FAIL: "Email 중복검사 실패",
  NO_EMAIL: '존재하지 않는 이메일 입니다.',
  RULE_MISS_MATCH_ID: "아이디 생성 규칙이 불일치합니다",
  RULE_MISS_MATCH_PW: "비밀번호 생성 규칙이 불일치합니다",
  RULE_MISS_MATCH_EMAIL: "이메일 생성 규칙이 불일치합니다",
  MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",

  /* User */
  READ_USER_SUCCESS: "사용자 조회 성공",
  READ_USER_ALL_SUCCESS: "전체 사용자 조회 실패",
  READ_USER_FAIL: "사용자 조회 성공",
  READ_USER_ALL_FAIL: "전체 사용자 조회 실패",
  UPDATE_USER_SUCCESS: "사용자 업데이트 성공",
  UPDATE_USER_FAIL: "사용자 업데이트 실패",
  DELETE_USER_SUCCESS: "사용자 삭제 성공",
  DELETE_USER_FAIL: "사용자 삭제 실패",
  FIND_EMAIL_SUCCESS: "사용자 이메일 찾기 성공",
  FIND_EMAIL_FAIL: "사용자 이메일 찾기 실패",
  RESET_PASSWORD_SUCCESS: "사용자 비밀번호 초기화 성공",
  RESET_PASSWORD_FAIL: "사용자 비밀번호 초기화 실패",
  EMAIL_CHECK_SUCCESS: "이메일 중복체크 성공",
  EMAIL_CHECK_FAIL: "이메일 중복체크 싱패",
  DELETE_ACCOUNT_SUCCESS: "계정 삭제 성공",
  DELETE_ACCOUNT_FAIL: "계정 삭제 실패",
  SET_MARKETING_SUCCESS: "마케팅 수신 설정 성공",
  SET_MARKETING_FAIL: "마케팅 수신 설정 실패",
  PW_CHECK_SUCCESS: "비밀번호 일치",
  PW_CHECK_FAIL: "비밀번호 체크 실패",
  CHANGE_PW_SUCCESS: "비밀번호 변경 성공",
  CHANGE_PW_FAIL: "비밀번호 변경 실패",
  GET_USER_SET_SUCCESS: "유저 계정 설정 조회 성공",
  GET_USER_SET_FAIL: "유저 계정 설정 조회 실패",
  NO_EMAIL: '존재하지 않는 이메일',
  UNAUTHORIZED: '인증 오류',

 /*MOMENT*/
  MOMENT_TITLE_TOO_LONG : "moment 제목 길이 초과",
  MOMENT_CONTENT_TOO_LONG : "moment 내용 길이 초과",
  MOMENT_REGISTER_SUCCESS : "moment 등록 성공",
  MOMENT_REGISTER_FAIL : "moment 등록 실패",
  FIND_ALL_MOMENTS_SUCCESS : "모든 moment 조회 성공",
  FIND_ALL_MOMENTS_FAIL : "모든 moment 조회 실패",
  NO_EXIST_MOMENT : '존재하지 않는 moment',
  FIND_MOMENT_BY_ID_SUCCESS : "해당 moment 조회 성공",
  FIND_MOMENT_BY_ID_FAIL : "해당 moment 조회 실패",
  NO_EXIST_BY_USER_ID_MOMENT : "존재하지 않는 user가 작성한 moment",
  FIND_MOMENT_BY_USER_ID_SUCCESS :"해당 user가 작성한 moment 조회 성공",
  FIND_MOMENT_BY_USER_ID_FAIL :"해당 user가 작성한 moment 조회 실패",
  FIND_ALL_MOMENTS_BY_ONE_BOOK_SUCCESS : "하나의 book에 해당하는 모든 moment 조회 성공 ",
  FIND_ALL_MOMENTS_BY_ONE_BOOK_FAIL : "하나의 book에 해당하는 모든 moment 조회 실패",
  UPDATE_MOMENT_SUCCESS : "moment 수정 성공",
  UPDATE_MOMENT_FAIL :"moment 수정 실패",
  DELETE_MOMENT_SUCCESS : "moment 삭제 성공",
  DELETE_MOMENT_FAIL : "moment 삭제 실패",

  /*BOOK*/
  NO_BOOK : "존재하지 않는 book"

}
