module.exports = {
  NULL_VALUE: "필요한 값이 없습니다.",
  OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",

  /* 회원가입 */
  SIGN_UP_SUCCESS: "회원 가입 성공.",
  SIGN_UP_FAIL: "회원 가입 실패.",
  SIGN_IN_SUCCESS: "로그인 성공.",
  SIGN_IN_FAIL: "로그인 실패.",
  USER_LOGOUT: "사용자 로그아웃",
  ALREADY_ID: "존재하는 ID 입니다.",
  CHECK_ID_SUCCESS: "ID 중복검사 성공",
  CHECK_ID_FAIL: "ID 중복검사 실패",
  ALREADY_PHONE: "존재하는 핸드폰 번호 입니다.",
  NO_USER: "존재하지않는 유저 id 입니다.",
  ALREADY_EMAIL: "이미 존재하는 이메일 입니다.",
  CHECK_EMAIL_SUCCESS: "Email 중복검사 성공",
  CHECK_EMAIL_FAIL: "Email 중복검사 실패",
  NO_EMAIL: '존재하지 않는 이메일 입니다.',
  RULE_MISS_MATCH_ID: "아이디 생성 규칙이 불일치합니다",
  RULE_MISS_MATCH_PW: "비밀번호 생성 규칙이 불일치합니다",
  RULE_MISS_MATCH_EMAIL: "이메일 생성 규칙이 불일치합니다",
  MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",

  /* User */
  FIND_USER_ALL_FAIL : "전체 사용자 조회 실패",
  FIND_USER_ALL_SUCCESS : "전체 사용자 조회 성공",
  FIND_USER_BY_USER_ID_SUCCESS : "특정 사용자 유저아이디 조회 성공",
  FIND_USER_BY_USER_ID_FAIL : "특정 사용자 유저아이디 조회 실패",
  FIND_FOLLOWING_BY_ID_SUCCESS : "특정 사용자가 팔로우한 유저 아이디 조회 성공",
  FIND_USER_BY_USER_EMAIL_FAIL : "특정 사용자 유저이메일 조회 실패",
  FIND_USER_BY_USER_EMAIL_SUCCESS : "특정 사용자 유저이메일 조회 성공",
  UPDATE_USER_FAIL : "사용자 정보 수정 실패",
  UPDATE_USER_SUCCESS : "사용자 정보 수정 성공",
  DELETE_USER_SUCCESS : "사용자 삭제 성공",
  DELETE_USER_FAIL : "사용자 삭제 실패",
  FOLLOW_USER_SUCCESS : "사용자  팔로우 삭제",
  FOLLOW_USER_FAIL : "사용자 팔로우 실패",
  UNAUTHORIZED: "사용자 인증 실패",

 /*MOMENT*/
  MOMENT_TITLE_TOO_LONG : "moment 제목 길이 초과",
  MOMENT_CONTENT_TOO_LONG : "moment 내용 길이 초과",
  MOMENT_REGISTER_SUCCESS : "moment 등록 성공",
  MOMENT_REGISTER_FAIL : "moment 등록 실패",
  FIND_ALL_MOMENTS_SUCCESS : "모든 moment 조회 성공",
  FIND_ALL_MOMENTS_FAIL : "모든 moment 조회 실패",
  NO_EXIST_MOMENT : '존재하지 않는 moment',
  FIND_MOMENT_BY_ID_SUCCESS : "해당 moment 조회 성공",
  FIND_MOMENT_BY_ID_FAIL : "해당 moment 조회 실패",
  NO_EXIST_BY_USER_ID_MOMENT : "존재하지 않는 user가 작성한 moment",
  FIND_MOMENT_BY_USER_ID_SUCCESS :"해당 user가 작성한 moment 조회 성공",
  FIND_MOMENT_BY_USER_ID_FAIL :"해당 user가 작성한 moment 조회 실패",
  FIND_ALL_MOMENTS_BY_ONE_BOOK_SUCCESS : "하나의 book에 해당하는 모든 moment 조회 성공 ",
  FIND_ALL_MOMENTS_BY_ONE_BOOK_FAIL : "하나의 book에 해당하는 모든 moment 조회 실패",
  UPDATE_MOMENT_SUCCESS : "moment 수정 성공",
  UPDATE_MOMENT_FAIL :"moment 수정 실패",
  DELETE_MOMENT_SUCCESS : "moment 삭제 성공",
  DELETE_MOMENT_FAIL : "moment 삭제 실패",

  /* BOOK */
  REGISTER_BOOK_SUCCESS : "모멘트북 등록 성공",
  REGISTER_BOOK_FAIL : "모멘트북 등록 실패",
  FIND_ALL_BOOK_SUCCESS : "전체 모멘트북 조회 성공",
  FIND_ALL_BOOK_FAIL : "전체 모멘트북 조회 실패",
  NO_EXIST_BOOK : "해당 모멘트북이 존재하지 않습니다.",
  FIND_BOOK_BY_ID_SUCCESS : "특정 모멘트북 조회 성공",
  FIND_BOOK_BY_ID_FAIL : "특정 모멘트북 조회 실패",
  FIND_BOOK_BY_USER_ID_SUCCESS : "특정 유저 모멘트북 조회 성공",
  FIND_BOOK_BY_USER_ID_FAIL : "특정 유저 모멘트북 조회 실패",
  UPDATE_BOOK_SUCCESS : "모멘트북 업데이트 성공",
  UPDATE_BOOK_FAIL : "모멘트북 업데이트 실패",
  DELETE_BOOK_SUCCESS : "모멘트북 삭제 성공",
  DELETE_BOOK_FAIL : "모멘트북 삭제 실패",
  SEARCH_BOOK_SUCCESS : "모멘트북 검색 성공",
  SEARCH_BOOK_FAIL : "모멘트북 검색 실패",
  TourStyle_REGISTER_SUCCESS :"여행 스타일 성공",

  /* HASHTAG */
  HASHTAG_REGISTER_SUCCESS : "해시태그 등록 성공",
  HASHTAG_REGISTER_FAIL : "해시태그 등록 실패",

  /* CATEGORY */
  REGISTER_CATEGORY_SUCCESS : "카테고리 등록 성공",
  REGISTER_CATEGORY_FAIL : "카테고리 등록 실패",
  FIND_CATEGORY_BY_USER_ID_SUCCESS : "특정 유저 카테고리 조회 성공",
  FIND_CATEGORY_BY_USER_ID_FAIL : "특정 유저 카테고리 조회 실패",
  UPDATE_Category_SUCCESS : "카테고리 업데이트 성공",
  UPDATE_Category_FAIL : "카테고리 업데이트 실패",
  DELETE_Category_SUCCESS : "카테고리 삭제 성공",
  DELETE_Category_FAIL : "카테고리 삭제 실패",
}
